### ISSUE TITLE
#Help finding czm2333#

### ISSUE THREAD

**Issue by czm23333** [Tacther/A-Repository-For-czm#7]
@czm2333 Hello? Are you there?
@Tacther is looking for you, I'm sure.
The reason that I'm sure he is looking for you is that @NaturalSelect and @iceBear67 have already made issues and pull requests to this repository to change _czm2333_ to _czm23333_ but he refused all of them.
So, if you see this issue, could you please come here to say something? Or, if I disturbed you, I'd like to say sorry to you.

**Comment by NaturalSelect** [comment]
funny

**Comment by Tacther** [comment]
OH，i forget to change the name of repository.it's a place for czm to create some issues.i think it's nothing. it's fun. I think, too. By the way.don't push issues while exam.are you agree? Many big men.

**Comment by NaturalSelect** [comment]
> OH，i forget to change the name of repository.it's a place for czm to create some issues.i think it's nothing. it's fun. I think, too. By the way.don't push issues while exam.are you agree? Many big men.

你还是说中文吧

**Comment by iceBear67** [comment]
xs

**Comment by czm23333** [comment]
@Tacther 你的Chinglish过于高深导致我看不懂，我觉得还是使用中文交流比较好

**Comment by Tacther** [comment]
我认为不行，因为用中文会影响你们这些大佬的形象

**Comment by Tacther** [comment]
并且我觉得你们这些鸡饭有点那个啥

**Comment by NaturalSelect** [comment]
> 我认为不行，因为用中文会影响你们这些大佬的形象

您就是驰名双标?

**Comment by Tacther** [comment]
有辱大佬形象

**Comment by Tacther** [comment]
对了icebear67不再来打个分支吗

**Comment by Tacther** [comment]
我认为非常好玩

**Comment by Tacther** [comment]
回复：您就是驰名双标?
       练家子啊，那是你的拿手活

**Comment by Tacther** [comment]
并且我是渣渣，不会用github的reply

**Comment by NaturalSelect** [comment]
你是不是只会优美中国话?

**Comment by Tacther** [comment]
抱歉抱歉

**Comment by czm23333** [comment]
@Tacther 快 继续秀你的操作 我都准备好了

**Comment by Tacther** [comment]
是的呢大佬

**Comment by iceBear67** [comment]
yygq壬qqn别在这瞎bb了我请你快点去准备你的傻逼中考复考在这yygq能拯救的了你的脑瘫命运?

**Comment by NaturalSelect** [comment]
> 是的呢大佬

我笑了，也许这就是tacther大佬吧

**Comment by Tacther** [comment]
嗯，我认为很有趣，压轴戏总是最后上，还是请大佬先秀

**Comment by iceBear67** [comment]
是啊是啊，大佬您快点上@Tacther

**Comment by czm23333** [comment]
当你的Chinglish遍布语法错误 是个人都看不懂的时候
我才决定使用中文交流
然后我才发现 原来你说话就是这样的 和语言无关

**Comment by iceBear67** [comment]
sfc114514位评审一同等待您的中等高级*CHIGLISH*秀

**Comment by iceBear67** [comment]
@Tacther

**Comment by czm23333** [comment]
或许这是人的本性如此 我不清楚
毕竟如果说一说你这点 马上你就会蹦出新的一堆没人看得懂的话来

**Comment by Tacther** [comment]
我不是

**Comment by Tacther** [comment]
因为我是chiglish大佬

**Comment by Tacther** [comment]
没办法

**Comment by czm23333** [comment]
对 你是大佬

**Comment by Ink-33** [comment]
Venu rigardi la simiojn.

**Comment by Tacther** [comment]
我没有陪大佬玩的义务

**Comment by iceBear67** [comment]
是是是你是**CHIGLISH**神仙你快点表演一段我好去DEBUG的时候笑着。

**Comment by czm23333** [comment]
你应该快速开始你的Chinglish秀 让我们一饱眼福

**Comment by Tacther** [comment]
so，再见

**Comment by NaturalSelect** [comment]
当tacther使用浮点数时，浮点数就没有了精度损失

**Comment by iceBear67** [comment]
你要没事你就别再我DEBUG的时候叫你*DAD*出来

**Comment by Tacther** [comment]
哦，那还有double

**Comment by Tacther** [comment]
草泥马

**Comment by Tacther** [comment]
好了有点失态，请大佬们自行口嗨

**Comment by czm23333** [comment]
等明年你中考的时候我希望你把中考英语成绩贴在这里
哦，对不起，我忘了，你已经“中考”了

**Comment by Tacther** [comment]
回见

**Comment by Tacther** [comment]
哦真不巧

**Comment by Tacther** [comment]
等到明年再到这里说吧

**Comment by czm23333** [comment]
> 好了有点失态，请大佬们自行口嗨

当你自嗨的时候说别人在口嗨 我打赌这是今年最搞笑的笑话

**Comment by Tacther** [comment]
是的很fun对吧

**Comment by Ink-33** [comment]
宁还要中考？

**Comment by Tacther** [comment]
错了应该是funny，毕竟我是chingish大佬是吧

**Comment by NaturalSelect** [comment]
> > 好了有点失态，请大佬们自行口嗨
> 
> 当你自嗨的时候说别人在口嗨 我打赌这是今年最搞笑的笑话

tacther大佬要考两次中考

**Comment by Ink-33** [comment]
> > > 好了有点失态，请大佬们自行口嗨
> > 
> > 当你自嗨的时候说别人在口嗨 我打赌这是今年最搞笑的笑话
> 
> tacther大佬要考两次中考

活到老，考到老

**Comment by iceBear67** [comment]
这位壬初二就中考保底清华北大咯

**Comment by Tacther** [comment]
> 宁还要中考？

可以别插话好吗?big man ink no.33

**Comment by czm23333** [comment]
> 是的很fun对吧

对对对 但是还缺了一个关键部分 现在还没有你的Chinglish秀来助兴 所以我希望你可以满足我这个垃圾一点小小的愿望

**Comment by iceBear67** [comment]
来力来力 chiglish *bigman*

**Comment by Ink-33** [comment]
> > 宁还要中考？
> 
> 可以别插话好吗?big man ink no.33

什么时候给我嫖AWS？

**Comment by Tacther** [comment]
哎，那不行，我说过

**Comment by Tacther** [comment]
我没有义务，也没有权利

**Comment by Tacther** [comment]
> > > 宁还要中考？
> > 
> > 
> > 可以别插话好吗?big man ink no.33
> 
> 什么时候给我嫖AWS？

你死的时候

**Comment by czm23333** [comment]
> > 宁还要中考？
> 
> 可以别插话好吗?big man ink no.33

你不是开这个仓库给人提issue的吗 怎么不让人说话了 世界驰名双标

**Comment by Tacther** [comment]
没让你提啊

**Comment by Ink-33** [comment]
> > > > 宁还要中考？
> > > 
> > > 
> > > 可以别插话好吗?big man ink no.33
> > 
> > 什么时候给我嫖AWS？
> 
> 你死的时候

可惜了，你妈得跟我一起死

**Comment by NaturalSelect** [comment]
驰名双标带师

**Comment by iceBear67** [comment]
#驰名双标就是@Tacther#

**Comment by Tacther** [comment]
没你秀

**Comment by iceBear67** [comment]
#@Tacther偷肖战内裤#

**Comment by czm23333** [comment]
> 没让你提啊

但是issue是每个人都可以提的

**Comment by Tacther** [comment]
now i have to offline，have a good time, big guys

**Comment by Ink-33** [comment]
> > > > > 宁还要中考？
> > > > 
> > > > 
> > > > 可以别插话好吗?big man ink no.33
> > > 
> > > 什么时候给我嫖AWS？
> > 
> > 你死的时候
> 
> 可惜了，你妈得跟我一起死

不好意西忘记了，你没有妈妈

**Comment by Tacther** [comment]
> > 没让你提啊
> 
> 但是issue是每个人都可以提的

那我只能保持沉默

**Comment by Tacther** [comment]
from now on

**Comment by czm23333** [comment]
忘了 你可是因为一个issue就可以删掉repo的人

**Comment by iceBear67** [comment]
b i g  g u y s

**Comment by Tacther** [comment]
> > > > > > 宁还要中考？
> > > > > 
> > > > > 
> > > > > 可以别插话好吗?big man ink no.33
> > > > 
> > > > 
> > > > 什么时候给我嫖AWS？
> > > 
> > > 
> > > 你死的时候
> > 
> > 
> > 可惜了，你妈得跟我一起死
> 
> 不好意西忘记了，你没有妈妈

不好意思啊小孤儿

**Comment by czm23333** [comment]
对不起 我忘记了

**Comment by Tacther** [comment]
没有精子就有一个新的小生命出现

**Comment by Ink-33** [comment]
> > > > > > > 宁还要中考？
> > > > > > 
> > > > > > 
> > > > > > 可以别插话好吗?big man ink no.33
> > > > > 
> > > > > 
> > > > > 什么时候给我嫖AWS？
> > > > 
> > > > 
> > > > 你死的时候
> > > 
> > > 
> > > 可惜了，你妈得跟我一起死
> > 
> > 不好意西忘记了，你没有妈妈
> 
> 不好意思啊小孤儿

对孤儿Tacther表示同情

**Comment by Tacther** [comment]
轰动整个生物界

**Comment by iceBear67** [comment]
哲学家@Tacther 要开始说经文法了

**Comment by czm23333** [comment]
> 没有精子就有一个新的小生命出现

这就是你在屏幕前:hand:的理由吗

**Comment by NaturalSelect** [comment]
> > > > > > > 宁还要中考？
> > > > > > 
> > > > > > 
> > > > > > 可以别插话好吗?big man ink no.33
> > > > > 
> > > > > 
> > > > > 什么时候给我嫖AWS？
> > > > 
> > > > 
> > > > 你死的时候
> > > 
> > > 
> > > 可惜了，你妈得跟我一起死
> > 
> > 
> > 不好意西忘记了，你没有妈妈
> 
> 不好意思啊小孤儿

难怪你说话这么难听，原来是没有🐴

**Comment by Tacther** [comment]
![-15e1e16d83e58b7c](https://user-images.githubusercontent.com/61813832/88505978-78e96200-d00b-11ea-919c-6ece12a0b6eb.jpg)

**Comment by Tacther** [comment]
我只能抱有这样的眼光看你

**Comment by czm23333** [comment]
别发表情了 你的Chinglish怎么还不开始

**Comment by iceBear67** [comment]
你配吗

**Comment by czm23333** [comment]
懂了 你不是人

**Comment by iceBear67** [comment]
issue已被录入web.archive.org永久保存、、、

**Comment by czm23333** [comment]
名 传 千 古 @Tacther

**Comment by Ink-33** [comment]
> issue已被录入web.archive.org永久保存、、、

没送到北极可惜了

**Comment by NaturalSelect** [comment]
求求你赶紧开始你的chinglish秀，我等不急了

**Comment by iceBear67** [comment]
[欣  赏  镜  像  版 ](https://web.archive.org/web/20200727051926/https://github.com/Tacther/A-Repository-For-czm/issues/7)

**Comment by Ink-33** [comment]
> [欣  赏  镜  像  版 ](https://web.archive.org/web/20200727051926/https://github.com/Tacther/A-Repository-For-czm/issues/7)

遗  臭  万  年  了，，，

**Comment by iceBear67** [comment]
延伸阅读：https://github.com/Tacther/A-Repository-For-czm/pull/4

**Comment by Tacther** [comment]
对了，说实话，像你们这种无缘无故挑血半他人的行径，说实话谁遗臭万年还真说不准呢

**Comment by Tacther** [comment]
exam ing、 sorry

**Comment by Tacther** [comment]
（存档我也得留一份
